@startuml
'https://plantuml.com/class-diagram

class Ship
class CargoShip
class CruiseShip

' Inheritance relationships
Ship <|-- CargoShip
Ship <|-- CruiseShip

class Ship {
  # shipName : String
  # yearBuilt : String

  + getShipName() : String
  + setShipName(String shipName) : void
  + getYearBuilt() : String
  + setYearBuilt(String yearBuilt) : void
  + toString() : String
  + printShip() : void
}

class CargoShip {
  - cargoCapacityInTonnage : int

  + getCargoCapacityInTonnage() : int
  + setCargoCapacityInTonnage(int cargoCapacityInTonnage) : void
  + toString() : String
}

class CruiseShip {
  - maxNumberPassengers : int

  + getMaxNumberPassengers() : int
  + setMaxNumberPassengers(int maxNumberPassengers) : void
  + toString() : String
}

@enduml